name: 'Fourth workflow'
on:
  workflow_run:
    workflows:
      - 'Third workflow'
    types:
      - completed

jobs:
  success-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Greetings
        run: echo "Success"
  failure-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Greetings
        run: echo "Fail"

