name: 'Ninth workflow'
on:
 push:
   branches:
     - main

jobs:
  first-commad:
    runs-on: ubuntu-latest
    steps:
      - name: "Print github object"
        id: context-expression
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
