name: 'Sixth workflow'
on:
  push:
    branches:
      - main
jobs:
  first-command:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Some text"
      - name: Second step
        run: |
          node -v
          npm -v

