name: "Tenth workflow"
on:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest
    environment: 'develop'
    steps:
      - name: "Print github env"
        run: |
          echo '${{ vars.CUSTOM_VAR }}'
          echo '${{ secrets.PASSWORD }}'
